### ISSUE TITLE
Meaning of pooling in pre-training step

### ISSUE THREAD

**Issue by teang1995** [wxl1999/UniCRS#2]
Hi  Xiaolei, thank you for your work. I'm interested in various works with knowledge graph.
Anyway, I have a question.  What is the meaning of the pooling in the pre-training step?

$$ h_{u} = Pooling[f(\tilde{C}_{pre} | \Theta_{plm} ; \Theta_{fuse})] $$  in this equation, I cannot understand the meaning of pooling, and find corresponding code in github. 

It would be very grateful indeed if you can give me anyhelp.
Best regards.
Yongtaek

**Comment by wxl1999** [comment]
Hi, thanks for your attention on our work.
Pooling means that we will merge the encodings of each token, for the DialoGPT model here, we will take the last token encoding as commonly done.
