### ISSUE TITLE
DBPedia link not accessible

### ISSUE THREAD

**Issue by min942773** [wxl1999/UniCRS#9]
Hi, thank you for sharing code.
I think DB Pedia link in readme file has beed changed.
Could you change it into [https://databus.dbpedia.org/dbpedia/mappings/mappingbased-objects/2021.09.01/mappingbased-objects_lang=en.ttl.bzip2](https://databus.dbpedia.org/dbpedia/mappings/mappingbased-objects/2021.09.01/mappingbased-objects_lang=en.ttl.bzip2)?

**Comment by wxl1999** [comment]
Thanks for your inform, I will change it!
